/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sppmanagement.view.admin;

import java.sql.Connection;
import java.util.Date;
import sppmanagement.dao.PetugasDAO;
import sppmanagement.db.Auth;
import sppmanagement.db.DB;
import sppmanagement.model.Petugas;
import sppmanagement.view.admin.CRUDKelas.CRUDKelasView;
import sppmanagement.view.admin.CRUDPetugas.CRUDPetugasView;
import sppmanagement.view.admin.CRUDSPP.CRUDSPPView;
import sppmanagement.view.admin.CRUDSiswa.CRUDSiswaView;

/**
 *
 * @author ASTANEW2
 */
public class AdminView extends javax.swing.JFrame {

//    PetugasDAO petugasDAO = new PetugasDAO();
    AdminController controller = new AdminController();

    /**
     * Creates new form AdminView
     */
    public AdminView() {
        Auth.check();

        initComponents();

        setLocationRelativeTo(null);

        tabelPembayaran.setAutoCreateRowSorter(true);
        tableHistoryPembayaranSiswa.setAutoCreateRowSorter(true);
        tableSiswa.setAutoCreateRowSorter(true);

        controller.setupVisibility(this);
        controller.loadTabelPembayaran(this);
        controller.loadTabelSiswa(this);
        
        dateTanggalBayar.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        labelJudul = new javax.swing.JLabel();
        panelKelolaData = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buttonOpenCRUDPetugas = new javax.swing.JButton();
        buttonOpenCRUDKelas = new javax.swing.JButton();
        buttonOpenCRUDSPP = new javax.swing.JButton();
        buttonOpenCRUDSiswa = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        textSearchSiswaNISN = new javax.swing.JTextField();
        btnSearchSiswa = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        labelUserNISN = new javax.swing.JLabel();
        labelUserNIS = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelUserNama = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        labelUserKelas = new javax.swing.JLabel();
        labelUserAlamat = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        labelUserTelepone = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        labelUserSPP = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        mainTabPane = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPembayaran = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableSiswa = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelNameNISNEntri = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateTanggalBayar = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        textJumlahBayar = new javax.swing.JTextField();
        btnAddEntry = new javax.swing.JButton();
        btnResetEntri = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bulanBayar = new com.toedter.calendar.JMonthChooser();
        jLabel8 = new javax.swing.JLabel();
        tahunBayar = new com.toedter.calendar.JYearChooser();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableHistoryPembayaranSiswa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pembayaran SPP");

        jPanel4.setMinimumSize(new java.awt.Dimension(350, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(350, 625));

        labelJudul.setBackground(new java.awt.Color(153, 204, 255));
        labelJudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelJudul.setForeground(new java.awt.Color(0, 153, 255));
        labelJudul.setText("Admin Pembayaran SPP");

        panelKelolaData.setBackground(new java.awt.Color(153, 204, 255));
        panelKelolaData.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 255, 0), null));
        panelKelolaData.setForeground(new java.awt.Color(255, 255, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kelola Data");

        buttonOpenCRUDPetugas.setText("Petugas");
        buttonOpenCRUDPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenCRUDPetugasActionPerformed(evt);
            }
        });

        buttonOpenCRUDKelas.setText("Kelas");
        buttonOpenCRUDKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenCRUDKelasActionPerformed(evt);
            }
        });

        buttonOpenCRUDSPP.setText("SPP");
        buttonOpenCRUDSPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenCRUDSPPActionPerformed(evt);
            }
        });

        buttonOpenCRUDSiswa.setText("Siswa");
        buttonOpenCRUDSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenCRUDSiswaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelKelolaDataLayout = new javax.swing.GroupLayout(panelKelolaData);
        panelKelolaData.setLayout(panelKelolaDataLayout);
        panelKelolaDataLayout.setHorizontalGroup(
            panelKelolaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKelolaDataLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(179, 179, 179))
            .addGroup(panelKelolaDataLayout.createSequentialGroup()
                .addGroup(panelKelolaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelKelolaDataLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonOpenCRUDSPP, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelKelolaDataLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(buttonOpenCRUDPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelKelolaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonOpenCRUDKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOpenCRUDSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                .addGap(125, 125, 125))
        );
        panelKelolaDataLayout.setVerticalGroup(
            panelKelolaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKelolaDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelKelolaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOpenCRUDPetugas)
                    .addComponent(buttonOpenCRUDSiswa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelKelolaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOpenCRUDSPP)
                    .addComponent(buttonOpenCRUDKelas))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(100, 595));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Cari Siswa");

        btnSearchSiswa.setText("Cari Siswa");
        btnSearchSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSiswaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Biodata Siswa");

        labelUserNISN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelUserNISN.setForeground(new java.awt.Color(153, 153, 153));
        labelUserNISN.setText("-");

        labelUserNIS.setText("-");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("NIS");

        labelUserNama.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelUserNama.setText("-");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Kelas");

        labelUserKelas.setText("-");

        labelUserAlamat.setText("-");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Alamat");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Telepone");

        labelUserTelepone.setText("-");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("SPP");

        labelUserSPP.setText("-");

        jLabel22.setText("NISN");

        btnRefresh.setBackground(new java.awt.Color(0, 204, 153));
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textSearchSiswaNISN)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelUserNISN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelUserNIS)
                                    .addComponent(labelUserKelas)
                                    .addComponent(labelUserAlamat)
                                    .addComponent(labelUserTelepone)
                                    .addComponent(labelUserSPP)))
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel22)
                            .addComponent(labelUserNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh))
                    .addComponent(btnSearchSiswa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textSearchSiswaNISN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchSiswa)
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUserNama, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUserNISN)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(labelUserNIS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(labelUserKelas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(labelUserAlamat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(labelUserTelepone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(labelUserSPP))
                .addContainerGap(196, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                        .addGap(115, 115, 115))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(panelKelolaData, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelJudul)
                .addGap(18, 18, 18)
                .addComponent(panelKelolaData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel4);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tabelPembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Petugas", "Siswa", "Tanggal Bayar", "Bulan Dibayar", "Tahun Dibayar", "SPP", "Jumlah Bayar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelPembayaran);
        if (tabelPembayaran.getColumnModel().getColumnCount() > 0) {
            tabelPembayaran.getColumnModel().getColumn(0).setMinWidth(10);
            tabelPembayaran.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        mainTabPane.addTab("Semua Pembayaran", jScrollPane2);

        tableSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NISN", "NIS", "Nama", "Kelas", "Alamat", "No Telp", "SPP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSiswaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableSiswa);

        mainTabPane.addTab("Daftar Siswa", jScrollPane3);

        jPanel2.setMinimumSize(new java.awt.Dimension(200, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 595));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Entri Pembayaran SPP");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Siswa");

        labelNameNISNEntri.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelNameNISNEntri.setText("-");

        jLabel5.setText("Tanggal Bayar");

        jLabel10.setText("Jumlah Bayar");

        textJumlahBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textJumlahBayarActionPerformed(evt);
            }
        });

        btnAddEntry.setText("Ok");
        btnAddEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEntryActionPerformed(evt);
            }
        });

        btnResetEntri.setText("Reset");
        btnResetEntri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetEntriActionPerformed(evt);
            }
        });

        jLabel6.setText("Tanggal Bayar");

        jLabel8.setText("Tanggal Bayar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateTanggalBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelNameNISNEntri))
                    .addComponent(textJumlahBayar)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnResetEntri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddEntry))
                    .addComponent(bulanBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addComponent(tahunBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelNameNISNEntri))
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateTanggalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bulanBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tahunBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textJumlahBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddEntry)
                    .addComponent(btnResetEntri))
                .addContainerGap(322, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(jPanel2);

        jScrollPane4.setPreferredSize(new java.awt.Dimension(600, 402));

        tableHistoryPembayaranSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Petugas", "Tanggal Bayar", "Bulan Dibayar", "Tahun Dibayar", "Jumlah Bayar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableHistoryPembayaranSiswa);

        jSplitPane2.setLeftComponent(jScrollPane4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        mainTabPane.addTab("Pembayaran Siswa", jPanel1);

        jSplitPane1.setRightComponent(mainTabPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOpenCRUDPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenCRUDPetugasActionPerformed
        new CRUDPetugasView().setVisible(true);
    }//GEN-LAST:event_buttonOpenCRUDPetugasActionPerformed

    private void buttonOpenCRUDKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenCRUDKelasActionPerformed
        new CRUDKelasView().setVisible(true);
    }//GEN-LAST:event_buttonOpenCRUDKelasActionPerformed

    private void buttonOpenCRUDSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenCRUDSiswaActionPerformed
        new CRUDSiswaView().setVisible(true);
    }//GEN-LAST:event_buttonOpenCRUDSiswaActionPerformed

    private void buttonOpenCRUDSPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenCRUDSPPActionPerformed
        new CRUDSPPView().setVisible(true);
    }//GEN-LAST:event_buttonOpenCRUDSPPActionPerformed

    private void btnSearchSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSiswaActionPerformed
        controller.searchUser(this);
    }//GEN-LAST:event_btnSearchSiswaActionPerformed

    private void textJumlahBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textJumlahBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textJumlahBayarActionPerformed

    private void btnResetEntriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetEntriActionPerformed
        controller.resetEntri(this);
    }//GEN-LAST:event_btnResetEntriActionPerformed

    private void btnAddEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEntryActionPerformed
        controller.addEntry(this);
    }//GEN-LAST:event_btnAddEntryActionPerformed

    private void tableSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSiswaMouseClicked
        controller.onTableSiswaClick(this);
    }//GEN-LAST:event_tableSiswaMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        controller.refresh(this);
    }//GEN-LAST:event_btnRefreshActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEntry;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnResetEntri;
    private javax.swing.JButton btnSearchSiswa;
    public com.toedter.calendar.JMonthChooser bulanBayar;
    private javax.swing.JButton buttonOpenCRUDKelas;
    private javax.swing.JButton buttonOpenCRUDPetugas;
    private javax.swing.JButton buttonOpenCRUDSPP;
    private javax.swing.JButton buttonOpenCRUDSiswa;
    public com.toedter.calendar.JDateChooser dateTanggalBayar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    public javax.swing.JLabel labelJudul;
    public javax.swing.JLabel labelNameNISNEntri;
    public javax.swing.JLabel labelUserAlamat;
    public javax.swing.JLabel labelUserKelas;
    public javax.swing.JLabel labelUserNIS;
    public javax.swing.JLabel labelUserNISN;
    public javax.swing.JLabel labelUserNama;
    public javax.swing.JLabel labelUserSPP;
    public javax.swing.JLabel labelUserTelepone;
    public javax.swing.JTabbedPane mainTabPane;
    public javax.swing.JPanel panelKelolaData;
    public javax.swing.JTable tabelPembayaran;
    public javax.swing.JTable tableHistoryPembayaranSiswa;
    public javax.swing.JTable tableSiswa;
    public com.toedter.calendar.JYearChooser tahunBayar;
    public javax.swing.JTextField textJumlahBayar;
    public javax.swing.JTextField textSearchSiswaNISN;
    // End of variables declaration//GEN-END:variables
}
